#file: noinspection YAMLSchemaValidation
name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run linter
        run: pnpm run lint
      - name: Run tests and coverage
        run: pnpm run coverage
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Secret check
        env:
          DEFINE_CHECK: ${{ secrets.SERVER_ADDRESS }}
        run: |
          if [ -z "$DEFINE_CHECK" ]; then
            echo "The secret is not defined. Skipping remaining deployment steps"
            echo "SECRET_NOT_DEFINED=true" >> "$GITHUB_ENV"
          else
            echo "The secret is defined. Continuing."
          fi
      - name: Checkout Repository
        if: env.SECRET_NOT_DEFINED != 'true'
        uses: actions/checkout@v4
      - name: Build and Push Docker Image
        if: env.SECRET_NOT_DEFINED != 'true'
        run: |
          docker build -t n2i-2023-api .
          docker login -u xen0xys -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag n2i-2023-api:latest xen0xys/n2i-2023-api:latest
          docker push xen0xys/n2i-2023-api:latest
      - name: SSH into Server and Deploy
        if: env.SECRET_NOT_DEFINED != 'true'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull xen0xys/n2i-2023-api:latest
            docker stop n2i-2023-api || true
            docker rm n2i-2023-api || true
            docker run -d -p 3000:3000 -e DOTENV_KEY=${{ secrets.DOTENV_KEY }} -v /home/${{ secrets.SERVER_USERNAME }}/keys:/home/keys --name n2i-2023-api --restart on-failure:2 xen0xys/n2i-2023-api:latest
